import json
import boto3
from botocore.exceptions import ClientError

# Initialize Cognito client
cognito = boto3.client('cognito-idp')

#Cognito User Pool details
CLIENT_ID = 'APP_CLIENT_ID_FROM_COGNITO'  # app client ID

def lambda_handler(event, context):
    try:
        username= event['username']
        password = event['password']
        # Sign in the user
        response = cognito.initiate_auth(
            ClientId=CLIENT_ID,
            AuthFlow='USER_PASSWORD_AUTH',
            AuthParameters={
                'USERNAME': username,
                'PASSWORD': password
            }
        )
        
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'User credentials verified successful!',
                'result': 'success'
            })
        }

    except ClientError as e:
        return {
            'status':400,
            'statusCode': 400,
            'body': json.dumps({
                'message': 'User Credentails failed to match!',
                'error': str(e)
            })
        }
