# The below AWS Lambda funtion verifies if the credentails i.e user email and password entered by the user in the first sign-in flow are correct 
import json
import boto3
from botocore.exceptions import ClientError

# Initialize Cognito client
cognito = boto3.client('cognito-idp')

# Cognito User Pool details
# The application client Id
CLIENT_ID = 'CLIENT_ID'  

def lambda_handler(event, context):
    print('The event is::')
    print(event)
    
    try:
        username= event['username']
        password = event['password']
        # Sign in the user
        response = cognito.initiate_auth(
            ClientId=CLIENT_ID,
            AuthFlow='USER_PASSWORD_AUTH',
            AuthParameters={
                'USERNAME': username,
                'PASSWORD': password
            }
        )
        return {
            'statusCode': 200,
            'body': json.dumps({
                'message': 'User credentials verified successful!',
                'result': 'success'
            })
        }

    except ClientError as e:
        # Handle errors (e.g., invalid credentials)
        print('Exception has occurred')
        print(e)
        return {
            'status':400,
            'statusCode': 400,
            'body': json.dumps({
                'message': 'User Credentails failed to match!',
                'error': str(e)
            })
        }
